name: Theme CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-theme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Theme ready
        run: echo "Theme repository is ready âœ…"
